<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\src\Offload.Models\Offload.Models.csproj" />
    <ProjectReference Include="..\..\src\Offload.Core\Offload.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Fixtures\**" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
